python das.py \
    --model_name_or_path "gpt2" \
    --toy_dataset \
    --layers "6;10" \
    --subspace_dim 64 \
    --positions "f4" \
    --intervention_offset 0 \
    --share_weights \
    --dropout 0 \
    --num_train_epochs 10 \
    --learning_rate 1e-3 \
    --batch_size 8 \
    --max_seq_length 256 \
    --logging_steps 10 \
    --output_dir=das \
    --use_wandb \
    --save_model